kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: simple-dotnet-mvc
  namespace: dev
  labels:
    app: simple-dotnet-mvc
    app.kubernetes.io/component: simple-dotnet-mvc
    app.kubernetes.io/instance: simple-dotnet-mvc
    app.kubernetes.io/part-of: simple-dotnet-mvc
    app.openshift.io/connects-to: database-app
    app.openshift.io/runtime: dotnet
spec:
  host: simple-dotnet-mvc-dev.apps.cluster-9462.9462.sandbox1207.opentlc.com
  to:
    kind: Service
    name: simple-dotnet-mvc
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFkTCCBHmgAwIBAgISBODG8UwkmjInQtZ4sO8fnfntMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjAyMTUwMjExMDRaFw0yMjA1MTYwMjExMDNaMDgxNjA0BgNVBAMT
      LWFwaS5jbHVzdGVyLTk0NjIuOTQ2Mi5zYW5kYm94MTIwNy5vcGVudGxjLmNvbTCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKmZosam0HN5GGtBHdEyGSjk
      D+F/XqlsyevLD9gz+2UgcAgNc0gCRjll7vltaFCcwL8UNmMf3avTQpLC52C/UEaV
      HZ8p3iebFU7JTIvNzk2ciBscApMqkyHymdi8xQZiFT2y3yrJUZEru49aIYpMUzjI
      eX4vbbYqTGvclc8skejTmxVAF22EcMQ5hYqsHzp7GZjYXeW+mKrxs7bjgdAYuekQ
      OlAAj6T1Ud1erUqMABh/FTsmkt6G0t4SRzLI56tPUwltdID9BDipspjuZu/JEUdv
      XJhHjNRzLwADTE1hBsxYft55r+wJf6nPEOPGwGp/A2XpLO8ip83KtrZuXmDFPXEC
      AwEAAaOCApkwggKVMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
      AQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUmA5DnnDE1x1wjcEb
      MGggpWgc324wHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYB
      BQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYI
      KwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wagYDVR0RBGMwYYIwKi5h
      cHBzLmNsdXN0ZXItOTQ2Mi45NDYyLnNhbmRib3gxMjA3Lm9wZW50bGMuY29tgi1h
      cGkuY2x1c3Rlci05NDYyLjk0NjIuc2FuZGJveDEyMDcub3BlbnRsYy5jb20wTAYD
      VR0gBEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYa
      aHR0cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHx
      AO8AdgBByMqx3yJGShDGoToJQodeTjGLGwPr60vHaPCQYpYG9gAAAX77XLjUAAAE
      AwBHMEUCIGrtd9f9hH7UeeS1DV+fOFYb8ZtuB9YZ/2b9/4Y6GvWTAiEA75cjLLi8
      eGytTWW6o8xC15sysCTkyfpNmkahqo6Xh50AdQApeb7wnjk5IfBWc59jpXflvld9
      nGAK+PlNXSZcJV3HhAAAAX77XLi4AAAEAwBGMEQCIE5DHW5RSvjq5NNd5NdbYC4b
      ePJ3NouaBZ5g7hLKF1ncAiApfLvV1k9Sf/4rYLUBbGI3Ype5BB2q+oByz2mNdQwW
      njANBgkqhkiG9w0BAQsFAAOCAQEAUcHVW4x4s8n3b9LvmaloCs5IKiXF0xD7+9/C
      0V5gdOPyXZyTi7Ki4ky9k6oDB59P9WMKo1T1qTDKII7QY4hV4PGr2SJPRRYJRoM2
      pRvSOda8DinFreAfQmyJB93BFjgiH24wN+3sz9DLIfh8LYHPV88WNCaOGairGfBO
      T6+CB7TWGNPw+G/LEQ132PZuE5LvaecQ9Vu6LQEDp+a2xBFfxL5qsX32d60/wacZ
      jqKqz/VSQdBJ/Nnugx2gTrS9ygmwlevucMexoYW9CmDm4ymdsKc36shiD8w8q0hi
      tNUhAw+HFyxAxl6j9At/D455wAEp9iyCaDXXe5Xe6Oj5piKUBg==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
      MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
      DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
      ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
      wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
      LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
      4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
      bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
      sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
      Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
      FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
      SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
      PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
      TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
      SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
      c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
      +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
      ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
      b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
      U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
      MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
      5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
      9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
      WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
      he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
      Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpmaLGptBzeRhr
      QR3RMhko5A/hf16pbMnryw/YM/tlIHAIDXNIAkY5Ze75bWhQnMC/FDZjH92r00KS
      wudgv1BGlR2fKd4nmxVOyUyLzc5NnIgbHAKTKpMh8pnYvMUGYhU9st8qyVGRK7uP
      WiGKTFM4yHl+L222Kkxr3JXPLJHo05sVQBdthHDEOYWKrB86exmY2F3lvpiq8bO2
      44HQGLnpEDpQAI+k9VHdXq1KjAAYfxU7JpLehtLeEkcyyOerT1MJbXSA/QQ4qbKY
      7mbvyRFHb1yYR4zUcy8AA0xNYQbMWH7eea/sCX+pzxDjxsBqfwNl6SzvIqfNyra2
      bl5gxT1xAgMBAAECggEAbVg1Xxg7uscvHC9OVwqSuA9ZwcvJrzgJczFnVMAm68sf
      D8IEOj/lIKp8iWmlYJu/lTIl4oCv/VDmUhLA9FpEGk2XXH+00BongbU82cHlqZor
      Ejdb3aAMXk24LMl/yZ7BDRde1IoZQZxNf53fk/ejjC+MTPOtK05YGQ6Ns5WLuOxw
      F3tmpvUKtCZVFYHx2RV4MdAo1ESKNYHffmEqROebVGpHwQ6xqKm6DD98Qn9oeZ5u
      F37hEXxVO7O3AY5EpHX+Dp3DTPQTPQE2ndHhhgR7WoNe4bey5rjnmDQJFJi7m5KT
      qE+pWRIjLL9uMC6jDzve/kWlNXi4KaKpVMIoXSDiMQKBgQDRU5RovCaeQ0IMKNxs
      V+L2eOGYzjr9FdWHawJgQLNKr7m6pAMzmHBPr8DJdjstXJugLb4fLIQjY1ff12AC
      1OTnNVj41ZwkqLpv3cmMzJN4mxpw4INnAE2av+DhiE+p2fGmMSiEwlnlykwL8FES
      ZVo492pfJ9Ru0AqMUdTBvJBU5QKBgQDPanbUyC+BWISwm8ThuyyXxagAmrIbDt9A
      nB4NykBod+WRnaPOmW//oKtFSMjwGboT6bv8h6Ia0mkabwOgfAcOAVDPe1MCfYsp
      EnKJAviEFem7shqT+VxasRukRPy2sXNvYHQ1V9g0jCI/3+czcL9UZoGLpxkEWDuj
      C1DCxf6pnQKBgQCTicVgzLyrb9xtlZ9G/esKrcjUWwdYurr154aVMQUt7w2Jb3CS
      PS9r+wR2+s5a+pr2G0eV0VqRVsPpEXSqikOMcx1yxZx4ejRuBHS6uLZ4m1nXlWcI
      gj4whG2MiPcdUG/yI1PbvuB+BkfzYj7CKI2e+UQQLZKdSCUnIcZDhxRzwQKBgHOn
      WrFVGmAWOo67nLF9i+To+r+zgoJh7Yx6QKvRzc4ypJhofRFTL0crkLSmXBy9S6uU
      1hR+kJ5CGwb5Rd1zqv9dLnEyw9uMo074kVLijC4ihdz596XxElUjklUrfnpkQgil
      kMa5v721MdfKAoIFaTonmi6DswhgJojIY3TnsBNlAoGAMrpEw4ZGJ4mveOe7DwFc
      I1B2GMyXW7BXVw2k8giyVh6ucLl+NdEsh81l8yKvoaSbopAb1ozeRd2s1N73vKVp
      ByGpmN0gkG33vLyYAhmK4IohG0QhxmF/9RHcIntJ2NUuc7oWkQWrEAjot9PQXnpq
      0XbTRv3aM0CFJJRaYcLUkns=
      -----END PRIVATE KEY-----
  wildcardPolicy: None
