FROM mcr.microsoft.com/dotnet/aspnet:5.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends libldap-2.4-2 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY ./bin/Release/net5.0/* /app

USER nobody
CMD ["dotnet", "SimpleDotnetMvc.dll"]