apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: database-service
spec:
  selector:
    app: database-app
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
